spring.datasource.url=jdbc:mysql://tokaido.proxy.rlwy.net:53713/railway
spring.datasource.username=root
spring.datasource.password=whAnGMVlqVbTfTcuehqeRvmfAXnzQJRg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

file.upload-dir=uploads